### ISSUE TITLE
No module named shapely.geometry.polygon

### ISSUE THREAD

**Issue by SeekPoint** [vshallc/PtrNets#3]
andy1028@andy1028-Envy:/media/andy1028/data1t/os_prj/github/PtrNets/pointer$ python ptrnets.py
Traceback (most recent call last):
  File "ptrnets.py", line 13, in <module>
    from shapely.geometry.polygon import Polygon
ImportError: No module named shapely.geometry.polygon

**Comment by vshallc** [comment]
pip install shapely

**Comment by SeekPoint** [comment]
fixed

**Comment by huangru** [comment]
Dear loveJasmine, how do you solve the above problem? I get into the same trouble.
Thanks

**Comment by SeekPoint** [comment]
@huangru 
pip install shapely

**Comment by huangru** [comment]
YES, I have Install the shapely at first, after that it still occured the above problem
